name: Build Core-PuerNya

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_gvisor,with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_clash_api,with_v2ray_api

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: PuerNya/sing-box
          ref: building        

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.5

      - name: get sing-box version
        id: version
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo version=$version >> $GITHUB_OUTPUT

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: checkout sing repository
        uses: actions/checkout@v4.1.1
        with:
          repository: PuerNya/sing
          ref: fix-interface
          path: sing

      - name: replace sing
        run: |
          sed -i 's/^\/\/replace github.com.*$/replace github.com\/sagernet\/sing => .\/sing/' go.mod          

      - name: Build core
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          VERSION=${version}
          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box

      - name: Rename file
        run: |
            mv sing-box singBox
            mv sing-box.exe singBox.exe
        
      - name: Upload android
        uses: actions/upload-artifact@v3
        with:
          name: singBox-android-arm64
          path: singBox

      - name: Upload windows
        uses: actions/upload-artifact@v3
        with:
          name: singBox-windows-amd64
          path: singBox.exe
