name: Build Core

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_gvisor,with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_clash_api,with_v2ray_api

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: jasmoli/sing-box
          ref: dev-next-xireiki


      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21.4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b
          add-to-path: false
          local-cache: false

      - name: Build core
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang
          VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -v -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${VERSION}' -s -w -buildid=" -tags ${TAGS} ./cmd/sing-box

      # - name: up to channel
      #   env:
      #     CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      #   run: |
      #     pip install pyTelegramBotAPI
      #     path="$GITHUB_WORKSPACE/sing-box"
      #     VERSION=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
      #     CAPTION=$(echo -e "sing-box version ${VERSION}\n\nEnvironment: go1.21.4 android-arm64/windows-amd64\nTags: ${TAGS}\nCGO: enabled")
      #     python3 $GITHUB_WORKSPACE/.github/scripts/tg_bot.py "$BOT_TOKEN" "$CHANNEL_ID" "$path" "$CAPTION"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sing-box_android
          path: sing-box

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sing-box_win
          path: sing-box.exe
